### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by tsouza** [apacheignite/yardstick-ignite#1] opened 2015-05-21 21:59 UTC
Hello,

I'm trying to run the benchmarks on EC2 (following the instructions presented on the webinar). After starting the servers, I've connected to one of them to check if everything was ok. Then I see the following docker logs:

```
Cloning into 'yardstick-ignite'...
fatal: unable to access 'https://github.com/tsouza/yardstick-ignite/': Could not resolve host: github.com
ls: cannot access */: No such file or directory
File config/benchmark-ec2.properties not found!
```

It seems that the docker container is not being to resolve github.com (although the host can resolve)

Any clue?

**Comment by ntikhonov** [comment] 2015-05-22 12:57
Hello, 
I see your point, but I cannot reproduce the issue. Could you, please, provide a more details about your amazon envirement: region, security rules? Make sure that you use one of the images listed on this page (https://github.com/yardstick-benchmarks/yardstick-docker section AMI).

**Comment by tsouza** [comment] 2015-05-22 15:43
Hello,
I did run using the related community amis. I'll try running the docker container directly.

I'm using us-east-1 with a permissive security group.

**Comment by tsouza** [comment] 2015-05-22 19:07
Hi there,

I could run benchmarks. But I didn't use the provided community AMIs. I started CoreOS instances instantiating the yardstick docker through cloud-config. 

To make it work, I also renamed benchmarks-ec2.properties to benchmark.properties. I also edited ignite-c2-config.xml so the discovery s3 bucketName configuration would come from environment vars.

**Comment by ntikhonov** [comment] 2016-02-20 10:47
I close this for now. Please let me know if you need any more details.

**Closed as completed** 2016-02-20 10:47 UTC
